### ISSUE TITLE
Лого проекта 

### ISSUE THREAD

**Issue by halconel** [halconel/OffTheRails#1]
Нужно создать лого для нашего проекта.

**Comment by Atom-Sergal** [comment]
![alt-текст](https://pp.userapi.com/c830609/v830609142/7208a/ywrd9CWXZiQ.jpg"тестовая версия")

**Comment by Atom-Sergal** [comment]
готов
https://pp.userapi.com/c830609/v830609142/7208a/ywrd9CWXZiQ.jpg
